# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Moses's Note
subtitle: 梦星河
description: 切不可与自己的平凡为敌，也不可与周遭的平庸为伍
author: Mr.Soong
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mrsoong.com
root: /
# permalink: posts/:year-:month-:day-:abbrlink.html
# permalink_defaults: posts/:year-:month-:day-:title.html

# abbrlink config
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - google458b3aacca3ccc3c.html
  - baidu_verify_3GW9vJowMe.html

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

google_site_verification: google458b3aacca3ccc3c.html
baidu-site-verification: baidu_verify_3GW9vJowMe.html

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts//默认:title.md
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
 编程: programming
 生活: life
 文学: literature
 诗: poem
 散文: prose
 其他: other
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

search: #搜索服务
  path: search.xml
  field: post
  format: html
  limit: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  #repository: git@github.com:mengxinghe/mengxinghe.github.io.git
  #branch: master  
  repo:
    #github: git@github.com:mengxinghe/mengxinghe.github.io.git,master
    coding: git@git.coding.net:mengxinghe/mengxinghe.coding.me.git,master
# _config.yml Next 主题配置文件++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
theme_config:

  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------

  # To get or check favicons visit: https://realfavicongenerator.net
  # Put your favicons into `hexo-site/source/` (recommend) or `hexo-site/themes/next/source/images/` directory.

  # Default NexT favicons placed in `hexo-site/themes/next/source/images/` directory.
  # And if you want to place your icons in `hexo-site/source/` root directory, you must remove `/images` prefix from pathes.

  # For example, you put your favicons into `hexo-site/source/images` directory.
  # Then need to rename & redefine they on any other names, otherwise icons from Next will rewrite your custom icons in Hexo.
  favicon: #网站图标  http://p3goxj4ar.bkt.clouddn.com/static
    small: /images/mx_favicon-16x16-my.png
    medium: /images/mx_favicon-32x32-my.png
    apple_touch_icon: /images/mx_favicon180x180-my.png
    safari_pinned_tab: /images/mx_logo-my.svg
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  #头像
  # Sidebar Avatar
  avatar:
    # in theme directory(source/images): /images/avatar.gif
    # in site  directory(source/uploads): /uploads/avatar.gif
    # You can also use other linking images.
    url: /images/mx_avatar.jpg
    # If true, the avatar would be dispalyed in circle. 
    rounded: true
    # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
    opacity: 1
    # If true, the avatar would be rotated with the cursor.
    rotated: true

  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    schedule: /schedule/ || calendar
    # sitemap: /sitemap.xml || sitemap
  # Enable/Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  # Set rss to false to disable feed link.
  # Leave rss as empty to use site's feed link.
  # Set rss to specific value if you have burned your feed already.
  rss: baidusitemap.xml

  # Set default keywords (Use a comma to separate)
  keywords: "mrsoong,unity,梦星河,游戏开发,hexo"
  # Schemes
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # Canvas-nest
  # Dependencies: https://github.com/theme-next/theme-next-canvas-nest
  canvas_nest: false

  # JavaScript 3D library.
  # Dependencies: https://github.com/theme-next/theme-next-three
  # three_waves
  three_waves: true
  # canvas_lines
  canvas_lines: false
  # canvas_sphere
  canvas_sphere: false

  # Only fit scheme Pisces
  # Dependencies: https://github.com/theme-next/theme-next-canvas-ribbon
  # Canvas-ribbon
  # size: The width of the ribbon.
  # alpha: The transparency of the ribbon.
  # zIndex: The display level of the ribbon.
  canvas_ribbon:
    enable: false
    size: 300
    alpha: 0.6
    zIndex: -1

  social:
    GitHub: https://github.com/mengxinghe || github
    E-Mail: mailto:moses@mrsoong.com || envelope
    WeiBo: http://weibo.com/609631239 || weibo
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #VK Group: https://vk.com/yourname || vk
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype



  # Wechat Subscriber
  #wechat_subscriber:
    #enabled: true
    #qcode: /path/to/your/wechatqcode ex. /uploads/wechat-qcode.jpg
    #description: ex. subscribe to my blog by scanning my public wechat account

  # Reward
  reward_comment: 坚持原创技术分享，您的支持将鼓励我继续创作！
  wechatpay: /images/mx_wechatpay.png
  alipay: /images/mx_alipay.jpg
  #bitcoin: /images/bitcoin.png

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  #valine:
  #  enable: true
  #  appid: OuiboUIcXsQX0eIEWUhKvIgC-gzGzoHsz # your leancloud application appid
  #  appkey: HvB1cg7mAdnpWfD3EFLgwhvY # your leancloud application appkey
  #  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  #  verify: false # Verification code
  #  placeholder: Just go go # comment box placeholder
  #  avatar: identicon # gravatar style
  #  guest_info: nick,mail,link # custom comment header
  # pageSize: 10 # pagination size

  # Show number of visitors to each article.
  # You can visit https://leancloud.cn get AppID and AppKey.
  leancloud_visitors:
    enable: true
    app_id: OuiboUIcXsQX0eIEWUhKvIgC-gzGzoHsz #<app_id>
    app_key: HvB1cg7mAdnpWfD3EFLgwhvY #<app_key>

  # Support for LiveRe comments system.
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere_uid: MTAyMC8zMzQxNy85OTcz #your uid
  # Social Links.
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
 
  # Baidu Share
  # Available value:
  #    button | slide
  # Warning: Baidu Share does not support https.
  baidushare: false
  ##type: button



  # Tencent analytics ID
  tencent_analytics: 65037408


  # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
  baidu_push: true

  # Local search
  # Dependencies: https://github.com/flashlab/hexo-generator-search
  local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 1

  footer:
    # Specify the date when the site was setup.
    # If not defined, current year will be used.
    since: 2018-2019

    # Icon between year and copyright info.
    icon: user

    # If not defined, will be used `author` from Hexo main config.
    copyright:
    # -------------------------------------------------------------
    # Hexo link (Powered by Hexo).
    powered: false

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: false
      # Version info of NexT after scheme info (vX.X.X).
      version: true
    # -------------------------------------------------------------
    # Any custom text can be defined here.
    custom_text: Hosted by <a target="_blank" rel="external nofollow" href="https://pages.coding.me"><b>Coding Pages</b></a>

  # Change headers hierarchy on site-subtitle (will be main site description) and on all post/pages titles for better SEO-optimization.
  seo: true

  # If true, will add site-subtitle to index page, added in main hexo config.
  # subtitle: Subtitle
  index_with_subtitle: true
  # Automatically excerpt description in homepage as preamble text.
  excerpt_description: true

  # Automatically Excerpt. Not recommend.
  # Please use <!-- more --> in the post to control excerpt accurately.
  auto_excerpt:
    enable: true
    length: 120

